
// -------------------------------------------------------

// let p = new Promise((resolve, reject) => {
//     let x = 2 + 3;
//     if(x==4) {
//         resolve("succes");
//     } else {
//         reject("Error")
//     }
// })


// p.then((message) => {
//     console.log(`Siamo nel then: ${message}`)
// }).catch((message) => {
//     console.log(`Siamo nel catch : ${message}`)
// })

// -------------------------------------------------------



